projects:
  reactamplified:
    schemaPath: amplify/backend/api/reactamplified/build/schema.graphql
    includes:
      - 'Y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
